### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Ivandou** [Ivandou/homepage#6]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by praddik** [comment]
Джо́зеф Робіне́тт Ба́йден-моло́дший, відомий як Джо Ба́йден (англ. Joseph "Joe" Robinette Biden, Jr.; нар. 20 листопада 1942, Скрентон, Пенсильванія, США) — американський державний і політичний діяч. Чинний президент США з 20 січня 2021 року.
