### ISSUE TITLE
Скласти блок контактної інформації.

### ISSUE THREAD

**Issue by Ivandou** [Ivandou/homepage#7]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by praddik** [comment]
Біографія на сайті Конгресу США
https://bioguide.congress.gov/search/bio/B000444

Виступ віцепрезидента Сполучених Штатів Америки Джозефа Робінетта Байдена у Верховній Раді України 8 листопада 2015 року
https://zbruc.eu/node/44794
