### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Ivandou** [Ivandou/homepage#8]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by praddik** [comment]
20—22 липня 2009 року 
відвідав Україну з робочим візитом. У ході переговорів президента України Віктора Ющенка та віцепрезидента США Джозефа Байдена домовлено створити Українсько-Американську Комісію зі стратегічного партнерства, перше засідання якої мало відбутися восени 2009.

21 квітня 2014 року
Прибув до Києва, щоб підтвердити підтримку нинішньому урядові України з боку Вашингтона.

7 червня 2014 року
Очолив Делегацію США на інавгурації новообраного президента України Петра Порошенка.

7 грудня 2015 року 
Джо Байден прибув в Україну з дводенним візитом. 8 грудня він виступив у Верховній Раді.

У вересні 2016 року 
Був впевнений, що Україна колись «надасть особливий статус Донбасу».

У січні 2018 року
Джо Байден заявив, що генпрокурора в Україні було звільнено на його вимогу й назвав його «сучим сином», очевидно маючи на увазі Віктора Шокіна.

У жовтні 2020 року 
Байден пообіцяв надати Україні летальну зброю та допомогти боротися з корупцією в разі своєї перемоги на виборах президента США.

У січні 2021 року 
Після перемоги на виборах Джо Байден під час телефонної розмови з президентом РФ В. Путіним прямо заявив про відкриту агресію Росії проти України, тоді як у Кремлі були не згодні з таким формулюванням.

У лютому 2021
На спеціальній сесії Мюнхенської конференції з безпеки, заявив, що підтримка територіальної цілісності України має величезне значення для Європи і США.

26 лютого
 Байден заявив, що його країна ніколи не визнає анексію українського півострова Крим Росією і США разом з Україною протистоятимуть агресивним діям РФ.

2 квітня 2021 року 
Байден провів першу після обрання президентом США розмову із президентом України Володимиром Зеленським. Глави держав обговорили повідомлення про накопичення російських військ на сході України та зусилля Зеленського щодо боротьби з корупцією.
