### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Ivandou** [Ivandou/homepage#9]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by praddik** [comment]
Особисте життя
2008 року був одним із найдосвідченіших сенаторів, пробувши на посаді представника від Делаверу 35 років. З вересня 1991 року він посідав посаду ад'юнкт-професора в школі правознавства при Вайденерському університеті, читав лекції з права. Байден був прихильником заборони носіння зброї цивільними особами, підтримував державне фінансування джерел альтернативної енергії. У серпні 2007 року Байден випустив книгу мемуарів «Обіцянки, які потрібно виконувати: у житті і в політиці» (англ. «Promises to Keep: On Life and Politics»).

Журналісти відзначали його демократичність: весь час своєї роботі в Сенаті він їздив із дому на роботу на електропоїзді. Байден завжди заявляв про свою строгу прихильність католицькій вірі й обіцяв «заткнути чотки в пасок будь-якому республіканцеві, який посміє дорікнути йому в маловір'ї». З річним доходом у 300 тисяч доларів він входить до числа найменш багатих сенаторів США.

Наприкінці 1972 року перша дружина Джо Байдена Нейлія і їхня дочка Наомі загинули в автокатастрофі. Сини Бо і Гантер теж знаходилися в машині і отримали серйозні травми, але вижили, і турбота про них стала першочерговою для Байдена.

Байден одружився вдруге. Через кілька років після загибелі першої дружини, 1977 року, Байден одружився з Джилл Трейсі Джекобс (Jill Tracy Jacobs). Джилл Трейсі — професорка англійської мови в Технічному громадському коледжі Делавера, з 1993 року вона очолює Байденське товариство з боротьби з раком грудей. У Байдена й Джилл Трейсі є дочка — Ешлі (Ashley). Старший син сенатора від першого шлюбу Джозеф Байден III (1969—2015) був генеральним прокурором штату Делавер і членом Демократичної партії. З 2008 року він оголосив про відхід на службу капітаном в Армійську національну гвардію від Делавера як генеральний суддя-адвокат, а також про свій намір служити в Іраку. Бо Байден помер від раку мозку в травні 2015 року. Другий син сенатора Роберт Гантер Байден 2006 року ввійшов до ради директорів американської залізничної компанії AMTRAK, у 2014—2019 роках входив до Ради директорів найбільшого приватного газодобувача в Україні «Бурісма Холдингс». Дочка Ешлі є соціальною працівницею. Крім того, у Байдена п'ятеро внуків: Наомі (Naomi), Фіннеґан (Finnegan), Роберта Мабель (Roberta Mabel), Наталі (Natalie) і Роберт Гантер (Robert Hunter).

Скандали
9 квітня 2020 року колишня помічниця Байдена Тара Рід звинуватила його в сексуальному насильстві. За її даними, це сталося 1993 року в підвалі офісного будинку Капітолію США, коли Байден був сенатором. До цього Тара заявляла про «недоречні дотики», але не говорила, що це було насильство. Тогочасні співробітники Байдена не підтвердили заяви Рід, заявивши, що подібна поведінка була не характерною для нього. Крім цього, багато хто зі співробітників не зміг згадати, щоб Рід працювала з ними.
